/**
 * server/seed.js
 * ─────────────────────────────────────────────────────────────────────────────
 * EmbeReady Seed Script
 * Run: npm run seed
 *
 * ⚠️  ALL DATA IN THIS FILE IS FICTIONAL DEMO DATA.
 *     It is placed within real Batangas City barangays for demonstration
 *     purposes only. No incident is attributed to any real person, business,
 *     or facility. Do not mistake seeded records for real incidents.
 *
 * Clears and re-populates:
 *   - barangays (15 barangays across Batangas City)
 *   - hazards (30 records, is_demo=1)
 *   - fire_history (10 records, is_demo=1)
 *   - emergency_contacts (from server/contacts.json)
 *   - risk_assessments (generated by rule-based engine)
 *   - preparedness_plans (from templates)
 * ─────────────────────────────────────────────────────────────────────────────
 */

'use strict';

require('dotenv').config();

const path = require('path');
const fs   = require('fs');
const db   = require('./db');
const { scoreHazard } = require('./ai/rules');
const { getPlan }     = require('./ai/templates');

// ─────────────────────────────────────────────────────────────────────────────
// 1. BARANGAYS (15 total)
// ─────────────────────────────────────────────────────────────────────────────
const BARANGAYS = [
    {
        name: 'Brgy. 1 (Poblacion)', classification: 'urban',
        center_lat: 13.7560, center_lng: 121.0565,
        evacuation_center_name: 'Brgy. 1 Covered Court'
    },
    {
        name: 'Brgy. 3 (Poblacion)', classification: 'urban',
        center_lat: 13.7572, center_lng: 121.0591,
        evacuation_center_name: 'Batangas City National High School — Main Campus'
    },
    {
        name: 'Brgy. 7 (Poblacion)', classification: 'urban',
        center_lat: 13.7548, center_lng: 121.0576,
        evacuation_center_name: 'Brgy. 7 Covered Court'
    },
    {
        name: 'Brgy. 12 (Poblacion)', classification: 'urban',
        center_lat: 13.7582, center_lng: 121.0601,
        evacuation_center_name: 'Brgy. 12 Hall / Covered Court'
    },
    {
        name: 'Brgy. 18 (Poblacion)', classification: 'urban',
        center_lat: 13.7555, center_lng: 121.0615,
        evacuation_center_name: 'Batangas City Central School'
    },
    {
        name: 'Alangilan', classification: 'urban',
        center_lat: 13.7841, center_lng: 121.0722,
        evacuation_center_name: 'Alangilan Elementary School'
    },
    {
        name: 'Kumintang Ibaba', classification: 'urban',
        center_lat: 13.7618, center_lng: 121.0508,
        evacuation_center_name: 'Kumintang Ibaba Barangay Hall'
    },
    {
        name: 'Kumintang Ilaya', classification: 'urban',
        center_lat: 13.7678, center_lng: 121.0538,
        evacuation_center_name: 'Kumintang Ilaya Covered Court'
    },
    {
        name: 'Pallocan West', classification: 'urban',
        center_lat: 13.7512, center_lng: 121.0478,
        evacuation_center_name: 'Pallocan West Barangay Hall'
    },
    {
        name: 'Pallocan East', classification: 'urban',
        center_lat: 13.7508, center_lng: 121.0548,
        evacuation_center_name: 'Pallocan East Elementary School'
    },
    {
        name: 'Santa Clara', classification: 'coastal',
        center_lat: 13.7578, center_lng: 121.0401,
        evacuation_center_name: 'Santa Clara Barangay Hall / Covered Court'
    },
    {
        name: 'Wawa', classification: 'coastal',
        center_lat: 13.7542, center_lng: 121.0316,
        evacuation_center_name: 'Wawa Barangay Hall'
    },
    {
        name: 'Bolbok', classification: 'transit',
        center_lat: 13.7438, center_lng: 121.0516,
        evacuation_center_name: 'Bolbok Covered Court / Barangay Hall'
    },
    {
        name: 'Tabangao', classification: 'industrial',
        center_lat: 13.7812, center_lng: 121.1095,
        evacuation_center_name: 'Tabangao Barangay Hall'
    },
    {
        name: 'Ilijan', classification: 'industrial',
        center_lat: 13.8058, center_lng: 121.1178,
        evacuation_center_name: 'Ilijan Barangay Hall / Covered Court'
    },
    {
        name: 'Sorosoro Ibaba', classification: 'upland',
        center_lat: 13.7268, center_lng: 121.0398,
        evacuation_center_name: 'Sorosoro Ibaba Elementary School'
    },
    {
        name: 'Tinga Labac', classification: 'upland',
        center_lat: 13.7178, center_lng: 121.0348,
        evacuation_center_name: 'Tinga Labac Barangay Hall'
    },
    {
        name: 'Dumantay', classification: 'upland',
        center_lat: 13.7092, center_lng: 121.0448,
        evacuation_center_name: 'Dumantay Barangay Hall'
    },
    // Calicanto added for contacts file completeness
    {
        name: 'Calicanto', classification: 'urban',
        center_lat: 13.7652, center_lng: 121.0612,
        evacuation_center_name: 'Calicanto Barangay Hall'
    }
];

// ─────────────────────────────────────────────────────────────────────────────
// 2. HAZARDS (30 records)
// All is_demo=1. Labels are generic — no real facility names as incident subjects.
// Photo filenames follow hazard-XX.jpg convention in /public/uploads/seed/
// ─────────────────────────────────────────────────────────────────────────────
// Status options: potential | active | contained | resolved
// Active fires (3): hazard-15, hazard-17, hazard-27

const HAZARDS_RAW = [
    // ── Brgy. 1 (Poblacion) ───────────────────────────────────────────────────
    {
        barangay: 'Brgy. 1 (Poblacion)',
        title:    'Dense residential row — faulty and tangled wiring',
        category: 'faulty_wiring', risk_level: 'heavy', status: 'potential',
        lat: 13.7558, lng: 121.0563,
        address:  'Residential block, near old commercial strip, Brgy. 1',
        description: 'Multiple adjacent wooden and mixed-material residences share overhead service drops with visible splice splints and improvised branch connections. Wires run through combustible wooden frames with no conduit. Several units show evidence of DIY sub-metering.',
        photo_url: '/uploads/seed/hazard-01.jpg'
    },
    // ── Brgy. 3 (Poblacion) ───────────────────────────────────────────────────
    {
        barangay: 'Brgy. 3 (Poblacion)',
        title:    'Overloaded electrical panel — mixed commercial-residential building',
        category: 'overloaded_outlets', risk_level: 'moderate', status: 'potential',
        lat: 13.7574, lng: 121.0593,
        address:  'Ground floor commercial unit, multi-storey building, Brgy. 3',
        description: 'A shared electrical panel with multiple tenants shows consistent breaker tripping. Daisy-chained power strips are used in the ground floor commercial space. Extension cords run across foot traffic areas and under floor mats.',
        photo_url: '/uploads/seed/hazard-02.jpg'
    },
    // ── Brgy. 7 (Poblacion) ───────────────────────────────────────────────────
    {
        barangay: 'Brgy. 7 (Poblacion)',
        title:    'Congested informal housing cluster, narrow internal alley',
        category: 'informal_settlement', risk_level: 'heavy', status: 'potential',
        lat: 13.7546, lng: 121.0578,
        address:  'Interior residential alley, Brgy. 7 Poblacion',
        description: 'A cluster of 12–15 closely spaced residential units constructed from wood, plywood, and tarpaulin. The main ingress alley is approximately 1.2 meters wide — impassable by fire apparatus. Open cooking stalls operate within the cluster. No visible fire extinguishers.',
        photo_url: '/uploads/seed/hazard-03.jpg'
    },
    // ── Brgy. 12 (Poblacion) ──────────────────────────────────────────────────
    {
        barangay: 'Brgy. 12 (Poblacion)',
        title:    'Improper LPG cylinder storage — ground floor of mixed-use building',
        category: 'lpg_storage', risk_level: 'heavy', status: 'potential',
        lat: 13.7584, lng: 121.0603,
        address:  'Ground floor retail space, mixed-use building, Brgy. 12',
        description: 'Seven LPG cylinders (11 kg) found stacked on their sides in an enclosed ground-floor storage room. The space is poorly ventilated, with a cooking area directly adjacent. No gas detector or fire extinguisher is visible. The space doubles as sleeping quarters at night.',
        photo_url: '/uploads/seed/hazard-04.jpg'
    },
    // ── Brgy. 18 (Poblacion) ──────────────────────────────────────────────────
    {
        barangay: 'Brgy. 18 (Poblacion)',
        title:    'Obstructed fire exit — market stall row',
        category: 'blocked_exit', risk_level: 'moderate', status: 'potential',
        lat: 13.7557, lng: 121.0617,
        address:  'Market stall corridor, Brgy. 18 commercial zone',
        description: 'A rear fire exit in a row of market stalls is blocked by stacked cardboard boxes, merchandise pallets, and plastic containers. The exit door handle is partially bound with rope. No fire exit signage is posted. The corridor has only one accessible egress at peak trading hours.',
        photo_url: '/uploads/seed/hazard-05.jpg'
    },
    // ── Alangilan (1) ─────────────────────────────────────────────────────────
    {
        barangay: 'Alangilan',
        title:    'Boarding house cluster — faulty wiring, overloaded circuits',
        category: 'faulty_wiring', risk_level: 'heavy', status: 'potential',
        lat: 13.7835, lng: 121.0715,
        address:  'Boarding house row, near university area, Alangilan',
        description: 'A row of student boarding houses shows multiple hazardous wiring conditions: single circuits serving 6–8 rooms, meters bypassed in two units, and exposed wire junctions above sleeping areas. Overloaded extensions are present in every room inspected. Smoke detectors are absent throughout.',
        photo_url: '/uploads/seed/hazard-06.jpg'
    },
    // ── Alangilan (2) ─────────────────────────────────────────────────────────
    {
        barangay: 'Alangilan',
        title:    'LPG cylinder stockpile — ground level near dormitory row',
        category: 'lpg_storage', risk_level: 'moderate', status: 'potential',
        lat: 13.7845, lng: 121.0730,
        address:  'Carenderia row, near student dormitories, Alangilan',
        description: 'A cluster of small eateries stores up to 15 LPG cylinders in an open area between cooking stalls and student dormitory entrances. Cylinders are not secured and some are stored on their side. One cylinder shows visible rust on the valve collar.',
        photo_url: '/uploads/seed/hazard-07.jpg'
    },
    // ── Kumintang Ibaba (1) ───────────────────────────────────────────────────
    {
        barangay: 'Kumintang Ibaba',
        title:    'Flammable material storage — roadside hardware supply yard',
        category: 'flammable_storage', risk_level: 'moderate', status: 'potential',
        lat: 13.7621, lng: 121.0511,
        address:  'Hardware supply yard, along main road, Kumintang Ibaba',
        description: 'Open-air storage of paint thinner, varnish, and construction solvents in a roadside yard adjacent to a residential block. No shade cover for direct sun. Containers are mostly unsealed 20-liter drums. No fire extinguisher, no "No Smoking" signage.',
        photo_url: '/uploads/seed/hazard-08.jpg'
    },
    // ── Kumintang Ibaba (2) ───────────────────────────────────────────────────
    {
        barangay: 'Kumintang Ibaba',
        title:    'Overloaded electrical panel — commercial building lobby',
        category: 'overloaded_outlets', risk_level: 'low', status: 'potential',
        lat: 13.7615, lng: 121.0505,
        address:  'Commercial building, Kumintang Ibaba',
        description: 'Panel box in a commercial building lobby shows visible scorch marks on two breaker slots. Building management reports two tripping incidents in the past month. The panel is not locked and is accessible to tenants. One breaker slot is fitted with a higher-amperage breaker than labeled.',
        photo_url: '/uploads/seed/hazard-09.jpg'
    },
    // ── Kumintang Ilaya ───────────────────────────────────────────────────────
    {
        barangay: 'Kumintang Ilaya',
        title:    'Dry cogon grass — road embankment and vacant lot edge',
        category: 'dry_grass', risk_level: 'low', status: 'potential',
        lat: 13.7682, lng: 121.0541,
        address:  'Road embankment and vacant lot, Kumintang Ilaya',
        description: 'A stretch of dry cogon grass and scrub vegetation along a road embankment borders the rear wall of several residential lots. The vegetation has not been cleared for at least one dry season cycle. Discarded cigarette ends are visible at the embankment base.',
        photo_url: '/uploads/seed/hazard-10.jpg'
    },
    // ── Pallocan West (1) ─────────────────────────────────────────────────────
    {
        barangay: 'Pallocan West',
        title:    'Market stall row — tangled overhead wiring, no fire exits',
        category: 'faulty_wiring', risk_level: 'heavy', status: 'potential',
        lat: 13.7514, lng: 121.0481,
        address:  'Market stall area, Pallocan West public market zone',
        description: 'A densely packed row of market stalls with overhead wiring running between stall frames using improvised connectors. Multiple taps to a single service drop. Combustible merchandise (fabric, dry goods, plastic goods) is stored against wiring routes. The area has one visible egress corridor that narrows to under 0.8 meters.',
        photo_url: '/uploads/seed/hazard-11.jpg'
    },
    // ── Pallocan West (2) ─────────────────────────────────────────────────────
    {
        barangay: 'Pallocan West',
        title:    'LPG cylinder stockpile — market backyard area',
        category: 'lpg_storage', risk_level: 'moderate', status: 'potential',
        lat: 13.7510, lng: 121.0476,
        address:  'Market backyard, Pallocan West',
        description: 'Approximately 20 LPG cylinders (mix of 11 kg and 22 kg) are stored in an uncovered, unventilated concrete enclosure at the rear of a market area. The enclosure is adjacent to a cooking area and is within 3 meters of a wooden structure. Some cylinders are stacked horizontally.',
        photo_url: '/uploads/seed/hazard-12.jpg'
    },
    // ── Pallocan East ─────────────────────────────────────────────────────────
    {
        barangay: 'Pallocan East',
        title:    'Commercial kitchen — improper ventilation, open flame near combustibles',
        category: 'flammable_storage', risk_level: 'moderate', status: 'potential',
        lat: 13.7506, lng: 121.0551,
        address:  'Restaurant row, Pallocan East commercial strip',
        description: 'Several adjacent commercial kitchens in a row of food establishments operate without proper range hood ventilation. Cooking grease residue is visible on walls and ceiling. Cardboard packaging and paper supplies are stored within 30 cm of active cooking surfaces.',
        photo_url: '/uploads/seed/hazard-13.jpg'
    },
    // ── Santa Clara (1) ───────────────────────────────────────────────────────
    {
        barangay: 'Santa Clara',
        title:    'Flammable goods storage — port-side warehouse',
        category: 'flammable_storage', risk_level: 'heavy', status: 'potential',
        lat: 13.7582, lng: 121.0406,
        address:  'Port-side warehouse area, Santa Clara, near Batangas Port',
        description: 'A warehouse near the port area stores paint, solvents, and petroleum-based lubricants without fire-rated wall separation. Ventilation openings are obstructed by stacked goods. No sprinkler system. Only one fire extinguisher (CO₂, expired) is visible. MSDS documents are not posted.',
        photo_url: '/uploads/seed/hazard-14.jpg'
    },
    // ── Santa Clara — ACTIVE FIRE ──────────────────────────────────────────────
    {
        barangay: 'Santa Clara',
        title:    'Structure fire — coastal shanty cluster',
        category: 'informal_settlement', risk_level: 'heavy', status: 'active',
        active_offset_minutes: -22,  // started 22 minutes ago (computed at seed time)
        lat: 13.7570, lng: 121.0395,
        address:  'Coastal shanty row, shoreline edge, Santa Clara',
        description: '⚠️ DEMO ACTIVE FIRE: A rapidly spreading fire is consuming three to four improvised wooden and tarpaulin structures in a coastal shanty cluster along the shoreline. Adjacent structures at immediate risk. Access is restricted by a narrow dirt lane.',
        photo_url: '/uploads/seed/hazard-15.jpg'
    },
    // ── Wawa (1) ──────────────────────────────────────────────────────────────
    {
        barangay: 'Wawa',
        title:    'Dense informal settlement — congested alleyways near shoreline',
        category: 'informal_settlement', risk_level: 'heavy', status: 'potential',
        lat: 13.7545, lng: 121.0322,
        address:  'Informal settlement cluster, Wawa coastal zone',
        description: 'A densely packed informal settlement of approximately 30–40 residential structures in close proximity to the shoreline. Structures are constructed primarily from salvaged lumber, plywood, and nipa. Internal lanes are 0.5–0.8 meters wide. Open cooking, candle use, and improvised electrical connections are observed throughout.',
        photo_url: '/uploads/seed/hazard-16.jpg'
    },
    // ── Wawa — ACTIVE FIRE ────────────────────────────────────────────────────
    {
        barangay: 'Wawa',
        title:    'Open burning — debris pile near residential cluster',
        category: 'illegal_burning', risk_level: 'heavy', status: 'active',
        active_offset_minutes: -9,  // started 9 minutes ago
        lat: 13.7538, lng: 121.0310,
        address:  'Vacant lot edge, Wawa coastal area',
        description: '⚠️ DEMO ACTIVE FIRE: An unattended debris-burning pile has expanded to dry surrounding vegetation within 4 meters of the nearest residential structure. Wind from the sea is accelerating spread toward the informal settlement.',
        photo_url: '/uploads/seed/hazard-17.jpg'
    },
    // ── Bolbok (1) ────────────────────────────────────────────────────────────
    {
        barangay: 'Bolbok',
        title:    'LPG and vehicle fuel storage — terminal service area',
        category: 'lpg_storage', risk_level: 'heavy', status: 'potential',
        lat: 13.7441, lng: 121.0519,
        address:  'Service and fuel storage area, transport terminal, Bolbok',
        description: 'A terminal service bay adjacent to a major transit hub stores LPG cylinders and vehicle fuel in close proximity. Fuel drums are unlabeled. The area is open to public access. Two motorcycles are parked within 1 meter of the fuel drum cluster. Cigarette butts are visible on the ground.',
        photo_url: '/uploads/seed/hazard-18.jpg'
    },
    // ── Bolbok (2) ────────────────────────────────────────────────────────────
    {
        barangay: 'Bolbok',
        title:    'Blocked emergency exits — commercial transit terminal structure',
        category: 'blocked_exit', risk_level: 'moderate', status: 'potential',
        lat: 13.7435, lng: 121.0513,
        address:  'Waiting area, commercial terminal building, Bolbok',
        description: 'Multiple fire exit doors in a busy transit terminal waiting area are obstructed by vendor stalls, baggage carousels, and parked trolleys. Exit signage is faded and not illuminated. The space has high pedestrian density during peak travel hours. Nearest unobstructed exit is approximately 40 meters from the far end of the waiting hall.',
        photo_url: '/uploads/seed/hazard-19.jpg'
    },
    // ── Tabangao (1) ──────────────────────────────────────────────────────────
    {
        barangay: 'Tabangao',
        title:    'Industrial chemical compound — open-yard drum storage',
        category: 'flammable_storage', risk_level: 'heavy', status: 'potential',
        lat: 13.7815, lng: 121.1098,
        address:  'Industrial compound, eastern industrial zone, Tabangao',
        description: 'A large open-yard compound contains numerous 200-liter drums labeled with flammable chemical markings. Some drums show corrosion and leakage staining at the base. The yard is adjacent to a perimeter road near a residential edge. No secondary containment bunding is visible. Fire suppression equipment is not accessible from the yard entrance.',
        photo_url: '/uploads/seed/hazard-20.jpg'
    },
    // ── Tabangao (2) ──────────────────────────────────────────────────────────
    {
        barangay: 'Tabangao',
        title:    'LPG and fuel pipeline corridor — proximate to residential zone',
        category: 'lpg_storage', risk_level: 'moderate', status: 'potential',
        lat: 13.7808, lng: 121.1085,
        address:  'Pipeline corridor edge, Tabangao industrial zone',
        description: 'An above-ground pipeline corridor runs within approximately 50 meters of the nearest residential structures. Informal housing has incrementally expanded toward the corridor over time. Pipeline inspection markers are present but condition of above-ground sections cannot be visually confirmed. Community awareness of the hazard is limited.',
        photo_url: '/uploads/seed/hazard-21.jpg'
    },
    // ── Ilijan (1) ────────────────────────────────────────────────────────────
    {
        barangay: 'Ilijan',
        title:    'Informal settlement — adjacent to power facility perimeter',
        category: 'informal_settlement', risk_level: 'heavy', status: 'potential',
        lat: 13.8052, lng: 121.1172,
        address:  'Informal settlement, perimeter zone, Ilijan industrial area',
        description: 'A cluster of approximately 20 informal structures has established itself adjacent to the perimeter fence of a power facility. Structures are within 15–30 meters of industrial infrastructure. Improvised electrical connections tap from the perimeter lighting circuit. Community has no formal evacuation plan.',
        photo_url: '/uploads/seed/hazard-22.jpg'
    },
    // ── Ilijan (2) ────────────────────────────────────────────────────────────
    {
        barangay: 'Ilijan',
        title:    'Flammable chemical drums — open yard, industrial compound',
        category: 'flammable_storage', risk_level: 'moderate', status: 'potential',
        lat: 13.8065, lng: 121.1183,
        address:  'Open storage yard, industrial compound, Ilijan',
        description: 'Approximately 30 chemical drums (labels partially degraded) are stored in an open yard with no secondary containment. Some drums are uncapped. The yard receives direct sunlight with ambient temperatures that can reach 38–40°C during dry season. The site is downwind of the settlement cluster.',
        photo_url: '/uploads/seed/hazard-23.jpg'
    },
    // ── Sorosoro Ibaba (1) ────────────────────────────────────────────────────
    {
        barangay: 'Sorosoro Ibaba',
        title:    'Dry brush and cogon hillside — upland fire risk zone',
        category: 'dry_grass', risk_level: 'moderate', status: 'potential',
        lat: 13.7271, lng: 121.0402,
        address:  'Upland hillside, Sorosoro Ibaba',
        description: 'An extensive area of cogon grass and dried scrub brush covers an upland hillside in Sorosoro Ibaba. The area has not been cleared or maintained. Steep gradient on the upper slope will accelerate any fire spread downhill toward residential areas at the hillside base. Multiple informal paths and trails pass through the area.',
        photo_url: '/uploads/seed/hazard-24.jpg'
    },
    // ── Sorosoro Ibaba — ACTIVE FIRE ──────────────────────────────────────────
    {
        barangay: 'Sorosoro Ibaba',
        title:    'Illegal burning of agricultural waste — spreading to brush',
        category: 'illegal_burning', risk_level: 'heavy', status: 'active',
        active_offset_minutes: -41,  // started 41 minutes ago
        lat: 13.7261, lng: 121.0391,
        address:  'Agricultural plot edge, Sorosoro Ibaba',
        description: '⚠️ DEMO ACTIVE FIRE: An agricultural waste burn on a plot edge has spread to adjacent cogon grassland. Fire is now moving upslope at an estimated 3–5 meters per minute. Smoke is visible from the main road. Nearest residential structures are approximately 80 meters downhill.',
        photo_url: '/uploads/seed/hazard-25.jpg'
    },
    // ── Tinga Labac (1) ───────────────────────────────────────────────────────
    {
        barangay: 'Tinga Labac',
        title:    'Dry grass slope — seasonal fire risk, upland zone',
        category: 'dry_grass', risk_level: 'moderate', status: 'potential',
        lat: 13.7181, lng: 121.0352,
        address:  'Hillside slope, Tinga Labac upland area',
        description: 'A hillside grass slope covering approximately 2 hectares in Tinga Labac consists of mature, fully dried cogon grass at the peak of dry season. The area borders a narrow road used for barangay access. Downslope, within 120 meters, are the nearest residential structures of the barangay.',
        photo_url: '/uploads/seed/hazard-26.jpg'
    },
    // ── Tinga Labac (2) ───────────────────────────────────────────────────────
    {
        barangay: 'Tinga Labac',
        title:    'Illegal burning near residential edge — dry season activity',
        category: 'illegal_burning', risk_level: 'moderate', status: 'contained',
        lat: 13.7172, lng: 121.0341,
        address:  'Residential edge lot, Tinga Labac',
        description: 'A recent illegal burning incident at the edge of a residential lot was contained by community members using water drums. Residual hotspot smoldering is still present. The neighboring lots have dry vegetation that could reignite. Community members have been advised but no formal barangay action has been recorded.',
        photo_url: '/uploads/seed/hazard-27.jpg'
    },
    // ── Dumantay ──────────────────────────────────────────────────────────────
    {
        barangay: 'Dumantay',
        title:    'Cogon brush — road-adjacent hillside, seasonal fire hazard',
        category: 'dry_grass', risk_level: 'low', status: 'potential',
        lat: 13.7095, lng: 121.0451,
        address:  'Road-adjacent hillside, Dumantay',
        description: 'A road-adjacent hillside in Dumantay is covered with seasonal cogon grass and scattered brush. The vegetation line reaches within 2–3 meters of the road shoulder. During peak dry season, the fire risk from passing vehicle exhaust or discarded materials is elevated. No firebreak is maintained along this road edge.',
        photo_url: '/uploads/seed/hazard-28.jpg'
    },
    // ── Calicanto (1) ─────────────────────────────────────────────────────────
    {
        barangay: 'Calicanto',
        title:    'Flammable chemical storage — roadside garage',
        category: 'flammable_storage', risk_level: 'moderate', status: 'potential',
        lat: 13.7655, lng: 121.0614,
        address:  'Roadside garage, Calicanto',
        description: 'A roadside vehicle repair garage stores paint thinner, mineral spirits, and used motor oil in unlabeled containers on open shelving adjacent to welding equipment. Smoking is observed among workers inside the garage. A single outdated dry powder extinguisher is mounted near the entrance but is partially blocked by a tire stack.',
        photo_url: '/uploads/seed/hazard-29.jpg'
    },
    // ── Kumintang Ilaya (2) ───────────────────────────────────────────────────
    {
        barangay: 'Kumintang Ilaya',
        title:    'Overloaded outlets — residential apartment building',
        category: 'overloaded_outlets', risk_level: 'low', status: 'potential',
        lat: 13.7675, lng: 121.0535,
        address:  'Residential apartment complex, Kumintang Ilaya',
        description: 'An apartment building with 12 units reports recurring tripped breakers on the ground and second floor. Tenants use multiple power strips and extension cords to compensate for limited outlet count per unit. The building\'s electrical plan is from the mid-1990s and has not been formally re-assessed for modern appliance loads.',
        photo_url: '/uploads/seed/hazard-30.jpg'
    }
];

// ─────────────────────────────────────────────────────────────────────────────
// 3. FIRE HISTORY (10 records — all fictional demo data)
// ─────────────────────────────────────────────────────────────────────────────
const FIRE_HISTORY_RAW = [
    {
        barangay: 'Brgy. 7 (Poblacion)',
        hazard_title: 'Congested informal housing cluster, narrow internal alley',
        incident_name: 'DEMO: Residential row fire — structure loss, 3 families displaced',
        incident_year: 2021, severity: 'heavy',
        damage_notes: 'Approximately three wooden structures in an interior block fully consumed. Fire reached a fourth structure before suppression. Access delays reported due to narrow alley.',
        lat: 13.7546, lng: 121.0577
    },
    {
        barangay: 'Pallocan West',
        hazard_title: 'Market stall row — tangled overhead wiring, no fire exits',
        incident_name: 'DEMO: Market stall row fire — 6 stalls destroyed',
        incident_year: 2022, severity: 'heavy',
        damage_notes: 'Six adjacent market stalls destroyed in a night fire. Origin traced to an overloaded wiring tap. Merchandise loss significant. No injuries reported.',
        lat: 13.7513, lng: 121.0480
    },
    {
        barangay: 'Santa Clara',
        hazard_title: 'Structure fire — coastal shanty cluster',
        incident_name: 'DEMO: Coastal shanty structure fire — 5 families displaced',
        incident_year: 2020, severity: 'heavy',
        damage_notes: 'Five shanty structures along the shoreline were destroyed. Wind from the bay accelerated spread. BFP suppression was delayed by narrow access. Families relocated to Brgy. Hall temporarily.',
        lat: 13.7569, lng: 121.0394
    },
    {
        barangay: 'Wawa',
        hazard_title: 'Dense informal settlement — congested alleyways near shoreline',
        incident_name: 'DEMO: Settlement night fire — partial structure loss',
        incident_year: 2019, severity: 'moderate',
        damage_notes: 'A cooking fire in an enclosed shanty spread to two adjacent units before community suppression. One minor injury. Two structures rendered uninhabitable.',
        lat: 13.7543, lng: 121.0320
    },
    {
        barangay: 'Alangilan',
        hazard_title: 'Boarding house cluster — faulty wiring, overloaded circuits',
        incident_name: 'DEMO: Boarding house electrical fire — partial damage',
        incident_year: 2023, severity: 'moderate',
        damage_notes: 'An electrical fire starting from a junction box above a second-floor room caused partial ceiling damage. Occupants evacuated successfully. Two rooms rendered uninhabitable. Wiring not up to code.',
        lat: 13.7836, lng: 121.0718
    },
    {
        barangay: 'Kumintang Ibaba',
        hazard_title: 'Flammable material storage — roadside hardware supply yard',
        incident_name: 'DEMO: Paint thinner fire — hardware yard, rapid suppression',
        incident_year: 2022, severity: 'low',
        damage_notes: 'A small fire ignited in a storage rack of paint thinner cans. Rapidly suppressed by nearby workers using a dry powder extinguisher. No structural damage. Regulatory notice issued.',
        lat: 13.7620, lng: 121.0510
    },
    {
        barangay: 'Tabangao',
        hazard_title: 'Industrial chemical compound — open-yard drum storage',
        incident_name: 'DEMO: Chemical drum fire — industrial zone, contained',
        incident_year: 2018, severity: 'heavy',
        damage_notes: 'Ignition of a leaking solvent drum spread to four adjacent drums. Industrial fire brigade responded before BFP arrival. No community impact but significant smoke dispersion reported toward residential area.',
        lat: 13.7812, lng: 121.1097
    },
    {
        barangay: 'Bolbok',
        hazard_title: 'LPG and vehicle fuel storage — terminal service area',
        incident_name: 'DEMO: Terminal service area fuel fire — vehicle damage',
        incident_year: 2021, severity: 'moderate',
        damage_notes: 'Spilled fuel near a vehicle maintenance bay ignited. Two vehicles partially burned. Terminal evacuated for approximately 2 hours. No injuries. BFP arrived in approximately 11 minutes.',
        lat: 13.7440, lng: 121.0518
    },
    {
        barangay: 'Sorosoro Ibaba',
        hazard_title: 'Dry brush and cogon hillside — upland fire risk zone',
        incident_name: 'DEMO: Hillside grass fire — 1.5 ha burned',
        incident_year: 2022, severity: 'moderate',
        damage_notes: 'An estimated 1.5 hectares of cogon grass burned on the Sorosoro Ibaba upland hillside during peak dry season. Community fire brigade managed containment before the fire reached residential structures. No injuries.',
        lat: 13.7268, lng: 121.0400
    },
    {
        barangay: 'Brgy. 12 (Poblacion)',
        hazard_title: 'Improper LPG cylinder storage — ground floor of mixed-use building',
        incident_name: 'DEMO: LPG minor leak and flash fire — no injuries',
        incident_year: 2023, severity: 'low',
        damage_notes: 'A minor LPG leak from a faulty regulator ignited briefly when a resident lit a match in an adjacent room. The fire self-extinguished when the cylinder valve was turned off. Scorch damage to one wall. BFP conducted post-incident inspection.',
        lat: 13.7583, lng: 121.0602
    }
];

// ─────────────────────────────────────────────────────────────────────────────
// SEED EXECUTION
// ─────────────────────────────────────────────────────────────────────────────

function seed() {
    console.log('\n[seed] Starting EmbeReady database seed...\n');

    // ── Clear demo data only (preserve user reports) ─────────────────────────
    db.exec(`
        DELETE FROM preparedness_plans WHERE hazard_id IN (SELECT id FROM hazards WHERE is_demo=1);
        DELETE FROM risk_assessments   WHERE hazard_id IN (SELECT id FROM hazards WHERE is_demo=1);
        DELETE FROM fire_history       WHERE is_demo=1;
        DELETE FROM hazards            WHERE is_demo=1;
        DELETE FROM emergency_contacts;
        DELETE FROM barangays;
    `);
    console.log('[seed] Cleared existing demo data.');

    // ── Insert barangays ──────────────────────────────────────────────────────
    const insertBrgy = db.prepare(`
        INSERT INTO barangays (name, classification, center_lat, center_lng, evacuation_center_name)
        VALUES (@name, @classification, @center_lat, @center_lng, @evacuation_center_name)
    `);
    const brgyMap = {};
    for (const b of BARANGAYS) {
        const result = insertBrgy.run(b);
        brgyMap[b.name] = result.lastInsertRowid;
    }
    console.log(`[seed] Inserted ${BARANGAYS.length} barangays.`);

    // ── Insert emergency contacts ─────────────────────────────────────────────
    const contactsPath = path.join(__dirname, 'contacts.json');
    const contactsRaw = fs.readFileSync(contactsPath, 'utf8').replace(/\/\*[\s\S]*?\*\/|([^:]|^)\/\/.*$/gm, '$1');
    const contacts = JSON.parse(contactsRaw);
    const insertContact = db.prepare(`
        INSERT INTO emergency_contacts
            (jurisdiction, agency_type, facility_name, phone_display, phone_dialable, is_placeholder, sort_order)
        VALUES (@jurisdiction, @agency_type, @facility_name, @phone_display, @phone_dialable, @is_placeholder, @sort_order)
    `);
    for (const c of contacts) {
        insertContact.run({
            ...c,
            is_placeholder: c.is_placeholder ? 1 : 0
        });
    }
    console.log(`[seed] Inserted ${contacts.length} emergency contacts.`);

    // ── Insert hazards ────────────────────────────────────────────────────────
    const insertHazard = db.prepare(`
        INSERT INTO hazards
            (ref_code, title, barangay_id, category, risk_level, status,
             lat, lng, address, description, photo_url, is_demo, active_started_at)
        VALUES (@ref_code, @title, @barangay_id, @category, @risk_level, @status,
                @lat, @lng, @address, @description, @photo_url, 1, @active_started_at)
    `);
    const insertAssessment = db.prepare(`
        INSERT INTO risk_assessments
            (hazard_id, overall_score, assessed_level, factors_json,
             confidence_level, reasoning_summary, engine, model_version)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    `);
    const insertPlan = db.prepare(`
        INSERT INTO preparedness_plans
            (hazard_id, before_steps_json, during_steps_json, after_steps_json,
             evacuation_tips_json, prohibited_actions_json, local_context_notes)
        VALUES (?, ?, ?, ?, ?, ?, ?)
    `);

    let hazardNum = 1;
    const hazardRefMap = {};  // title → id (for fire history lookup)

    for (const h of HAZARDS_RAW) {
        const brgyId = brgyMap[h.barangay];
        if (!brgyId) {
            console.warn(`[seed] WARNING: barangay "${h.barangay}" not found, skipping hazard "${h.title}"`);
            continue;
        }

        // Compute active_started_at for active fires
        let active_started_at = null;
        if (h.status === 'active' && h.active_offset_minutes) {
            const dt = new Date(Date.now() + h.active_offset_minutes * 60 * 1000);
            active_started_at = dt.toISOString();
        }

        const ref_code = `HZ-${String(hazardNum).padStart(4, '0')}`;
        const result = insertHazard.run({
            ref_code,
            title:    h.title,
            barangay_id: brgyId,
            category: h.category,
            risk_level: h.risk_level,
            status:   h.status,
            lat:      h.lat,
            lng:      h.lng,
            address:  h.address,
            description: h.description,
            photo_url: h.photo_url,
            active_started_at
        });
        const hazardId = result.lastInsertRowid;
        hazardRefMap[h.title] = hazardId;

        // Run rule-based assessment
        const brgyRow = { name: h.barangay, classification: BARANGAYS.find(b=>b.name===h.barangay)?.classification || 'urban' };
        const assessment = scoreHazard({ category: h.category, risk_level: h.risk_level, status: h.status }, brgyRow, 0);
        insertAssessment.run(
            hazardId,
            assessment.overall_score,
            assessment.assessed_level,
            assessment.factors_json,
            assessment.confidence_level,
            assessment.reasoning_summary,
            assessment.engine,
            assessment.model_version
        );

        // Insert preparedness plan
        const plan = getPlan(h.category, h.barangay);
        insertPlan.run(
            hazardId,
            plan.before_steps_json,
            plan.during_steps_json,
            plan.after_steps_json,
            plan.evacuation_tips_json,
            plan.prohibited_actions_json,
            plan.local_context_notes
        );

        hazardNum++;
    }
    console.log(`[seed] Inserted ${hazardNum - 1} hazards with assessments and plans.`);

    // ── Insert fire history ───────────────────────────────────────────────────
    const insertHistory = db.prepare(`
        INSERT INTO fire_history
            (hazard_id, barangay_id, incident_name, incident_year, severity, damage_notes, lat, lng, is_demo)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1)
    `);
    for (const fh of FIRE_HISTORY_RAW) {
        const brgyId   = brgyMap[fh.barangay] || null;
        const hazardId = hazardRefMap[fh.hazard_title] || null;
        insertHistory.run(
            hazardId, brgyId,
            fh.incident_name, fh.incident_year, fh.severity,
            fh.damage_notes, fh.lat, fh.lng
        );
    }
    console.log(`[seed] Inserted ${FIRE_HISTORY_RAW.length} fire history records.`);

    // ── Print photo mapping ───────────────────────────────────────────────────
    printPhotoMapping();

    console.log('\n[seed] ✅ Seed complete! Run: npm run dev\n');
}

function printPhotoMapping() {
    console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('  PHOTO FILE → HAZARD TITLE MAPPING');
    console.log('  Place photos in: ./public/uploads/seed/');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    HAZARDS_RAW.forEach((h, i) => {
        const num  = String(i + 1).padStart(2, '0');
        const file = `hazard-${num}.jpg`;
        const tag  = h.status === 'active' ? ' [ACTIVE FIRE]' : '';
        console.log(`  ${file.padEnd(18)} → ${h.barangay.padEnd(25)} | ${h.title.slice(0,55)}${tag}`);
    });
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
}

seed();
